name: Run R script monthly1

on:
  schedule:
    - cron: '33 20 25 * *'  # Ejecuta día 26 de cada mes a las 00:00 UTC

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'  # Cambia a la versión de R que necesites

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("tidyverse", "httr", "jsonlite", "rjson", "ggplot2"))'  # Ajusta las librerías que necesite tu script

      - name: Run poblacion.R script
        run: |
          Rscript poblacion.R
