name: Run R script monthly4

on:
  schedule:
    - cron: '19 1 29 * *'  # Ejecuta día 28 de cada mes a las 00:00 UTC

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
      - name: Prope
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.1'  # Cambia a la versión de R que necesites

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("tidyverse", "jsonlite", "dplyr", "ggplot2", "rjson"))'  # Ajusta las librerías que necesite tu script

      - name: Run poblacion.R script
        run: |
          Rscript poblacion.R
      - name: Commit and push plot
        run: |
          git config --global user.name "IvanParedesR"
          git config --global user.email "ivanresendiz25@gmail.com"
          git add p.png
          git commit -m "Add generated plot"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
